# TravisCI is run without tests because of some issues with threading
sudo: false
language: csharp
solution: MeasureMap.sln
mono: none
dotnet: 3.0.100

notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: never #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
    
install:
  - sudo apt-get install -qq dotnet-sdk-2.0.0
  - dotnet restore

script:
  - dotnet build
#  - dotnet test