# Travis is now container based which doesn't support sudo
sudo: false
language: csharp
solution: MeasureMap.sln
mono: none
#dotnet: 2.1.502
#dotnet: 2.0.0
dotnet: 3.0.100
dist: trusty

notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: never #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
    
install:
#  - nuget restore MeasureMap.sln
  - dotnet restore
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner

script:
#  - dotnet restore
  - dotnet build
#  - xbuild /p:Configuration=Release MeasureMap.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./src/Tests/MeasureMap.UnitTest/bin/Release/MeasureMap.UnitTest.dll