language: csharp
solution: MeasureMap.sln
 
install:
  - sudo apt-get install nunit-console
  - nuget restore MeasureMap.sln
 
script:
  - xbuild MeasureMap.sln
  - nunit-console ./src/Tests/MeasureMap.UnitTest/bin/Release/MeasureMap.UnitTest.dll