# http://www.appveyor.com/docs/appveyor-yml


# version format
version: 1.7.0

image:
  - Visual Studio 2022

# branches to build
branches:
  # whitelist
  only:
    - master
    - dev

# Do not build on tags (GitHub only)
skip_tags: true

install:
  - dotnet tool install Nuke.GlobalTool --global --version 6.0.1 --no-cache

before_build:
  - dotnet restore ./build/_build.csproj

build_script:
  - cmd: nuke compile --isrc true --version {version} --buildno {build}

artifacts:
  - path: src\MeasureMap\bin\Release\netstandard2.0\MeasureMap.dll
    name: MeasureMap.dll

  # pushing all *.nupkg files in directory
  - path: '.\*.nupkg'
