# http://www.appveyor.com/docs/appveyor-yml

environment:
  base_version: 3.0.0

# version format
version: $(base_version).{build}

image:
  - Visual Studio 2022

for:
  - 
    # branches to build
    branches:
      # whitelist
      only:
        - dev

    # Do not build on tags (GitHub only)
    skip_tags: true

    install:
      - dotnet tool install Nuke.GlobalTool --global --version 9.0.3 --no-cache

    before_build:
      - dotnet restore ./build/_build.csproj

    build_script:
      - nuke Release --isrc true --buildno "%APPVEYOR_BUILD_NUMBER%" --version "%base_version%"

    test: off

  - 
    # branches to build
    branches:
      # whitelist
      only:
        - master

    # Do not build on tags (GitHub only)
    skip_tags: true

    install:
      - dotnet tool install Nuke.GlobalTool --global --version 9.0.3 --no-cache

    before_build:
      - dotnet restore ./build/_build.csproj

    build_script:
      - nuke Release --isrc false --buildno "%APPVEYOR_BUILD_NUMBER%" --version "%base_version%"

    test: off
  - 
    # branches to build
    branches:
      # whitelist
      except:
        - master
        - dev

    # Do not build on tags (GitHub only)
    skip_tags: true

    install:
      - dotnet tool install Nuke.GlobalTool --global --version 9.0.3 --no-cache

    before_build:
      - dotnet restore ./build/_build.csproj

    build_script:
      - nuke Test --isrc false --buildno "%APPVEYOR_BUILD_NUMBER%" --version "%base_version%"

    test: off

artifacts:
  - path: src\MeasureMap\bin\Release\netstandard2.0\MeasureMap.dll
    name: MeasureMap.dll
  - path: src\MeasureMap\bin\Release\netstandard2.0\MeasureMap.xml
    name: MeasureMap.xml
  # pushing all *.nupkg files in directory
  - path: 'src\MeasureMap\bin\Release\*.nupkg'
